name: kinetics_modelling
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - typer
  - loguru
  - polars
  - numpy
  - scikit-learn
  - pandas
  - vegafusion
  - pyarrow
  - ipykernel
  - altair
  - tqdm
  - ruff

