name: kinetics_modelling
channels:
  - conda-forge
  - gwforg
dependencies:
  - python=3.12.7
  - polars
  - numpy
  - scikit-learn
  - vegafusion
  - ipykernel
  - altair
  - tqdm
  - ruff
  - gwf
  - pysam
  - loguru
  - python-dotenv
  - line_profiler
  - pip
  - pip:
      - -e .

